//
//  TempoarlDatabase_AboutContinuitySheet.swift
//  VistaBridge
//
//  Created by 齐晴 on 17/5/3.
//  Copyright © 2017年 GaryQi. All rights reserved.
//

import Foundation
let CONTINUITY_SHEET_INFOS : [String:[ContinuitySheetRecording]] = [
    "0701" :[
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C001", sceneNumber: 13, shotNumber: 1, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C002", sceneNumber: 13, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C003", sceneNumber: 13, shotNumber: 1, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C004", sceneNumber: 13, shotNumber: 1, takeNumber: 4, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C005", sceneNumber: 13, shotNumber: 1, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C006", sceneNumber: 13, shotNumber: 1, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C007", sceneNumber: 13, shotNumber: 1, takeNumber: 7, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C008", sceneNumber: 13, shotNumber: 2, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C009", sceneNumber: 13, shotNumber: 2, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C010", sceneNumber: 13, shotNumber: 2, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C011", sceneNumber: 13, shotNumber: 2, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C012", sceneNumber: 13, shotNumber: 2, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C013", sceneNumber: 13, shotNumber: 2, takeNumber: 6, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0701",rollNumber:"A002", fileNumber:"C014", sceneNumber: 13, shotNumber: 2, takeNumber: 7, result:.ok , synopsis:" " , shotSize:.bcu),
    ],
    "0702" :[
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A003", fileNumber:"C001", sceneNumber: 13, shotNumber: 3, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A003", fileNumber:"C002", sceneNumber: 13, shotNumber: 3, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A003", fileNumber:"C003", sceneNumber: 13, shotNumber: 3, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A003", fileNumber:"C004", sceneNumber: 13, shotNumber: 3, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A003", fileNumber:"C005", sceneNumber: 13, shotNumber: 4, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A003", fileNumber:"C006", sceneNumber: 13, shotNumber: 4, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A003", fileNumber:"C007", sceneNumber: 11, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A003", fileNumber:"C008", sceneNumber: 11, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A003", fileNumber:"C009", sceneNumber: 11, shotNumber: 1, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A003", fileNumber:"C010", sceneNumber: 11, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A003", fileNumber:"C011", sceneNumber: 11, shotNumber: 2, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C001", sceneNumber: 11, shotNumber: 2, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C002", sceneNumber: 11, shotNumber: 2, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C003", sceneNumber: 11, shotNumber: 2, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C004", sceneNumber: 11, shotNumber: 2, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C005", sceneNumber: 11, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C006", sceneNumber: 11, shotNumber: 3, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C007", sceneNumber: 11, shotNumber: 3, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C008", sceneNumber: 11, shotNumber: 4, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C009", sceneNumber: 11, shotNumber: 4, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C010", sceneNumber: 11, shotNumber: 4, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C011", sceneNumber: 11, shotNumber: 4, takeNumber: 4, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C012", sceneNumber: 11, shotNumber: 5, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C013", sceneNumber: 11, shotNumber: 5, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C014", sceneNumber: 11, shotNumber: 5, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C015", sceneNumber: 11, shotNumber: 5, takeNumber: 4, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C016", sceneNumber: 11, shotNumber: 5, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0702",rollNumber:"A004", fileNumber:"C017", sceneNumber: 11, shotNumber: 5, takeNumber: 6, result:.kp , synopsis:" " , shotSize:.ls),
    ],
    "0703" :[
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A005", fileNumber:"C001", sceneNumber: 20, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A005", fileNumber:"C002", sceneNumber: 20, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A006", fileNumber:"C001", sceneNumber: 20, shotNumber: 1, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A006", fileNumber:"C002", sceneNumber: 20, shotNumber: 1, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A006", fileNumber:"C003", sceneNumber: 20, shotNumber: 1, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A006", fileNumber:"C004", sceneNumber: 20, shotNumber: 1, takeNumber: 6, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A006", fileNumber:"C005", sceneNumber: 20, shotNumber: 1, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A006", fileNumber:"C006", sceneNumber: 20, shotNumber: 2, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A006", fileNumber:"C007", sceneNumber: 20, shotNumber: 2, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A006", fileNumber:"C008", sceneNumber: 20, shotNumber: 3, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A006", fileNumber:"C009", sceneNumber: 20, shotNumber: 4, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0703",rollNumber:"A006", fileNumber:"C010", sceneNumber: 20, shotNumber: 4, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.mcu),
    ],
    "0704" :[
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C001", sceneNumber: 25, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C002", sceneNumber: 25, shotNumber: 1, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C003", sceneNumber: 25, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C004", sceneNumber: 25, shotNumber: 2, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C005", sceneNumber: 25, shotNumber: 2, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C006", sceneNumber: 25, shotNumber: 2, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C007", sceneNumber: 25, shotNumber: 2, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C008", sceneNumber: 25, shotNumber: 2, takeNumber: 6, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C009", sceneNumber: 25, shotNumber: 3, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C010", sceneNumber: 27, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C011", sceneNumber: 27, shotNumber: 1, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C012", sceneNumber: 27, shotNumber: 1, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C013", sceneNumber: 27, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C014", sceneNumber: 27, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A007", fileNumber:"C015", sceneNumber: 27, shotNumber: 2, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A008", fileNumber:"C001", sceneNumber: 27, shotNumber: 2, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A008", fileNumber:"C002", sceneNumber: 27, shotNumber: 2, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A008", fileNumber:"C003", sceneNumber: 27, shotNumber: 2, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A008", fileNumber:"C004", sceneNumber: 27, shotNumber: 2, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A008", fileNumber:"C005", sceneNumber: 30, shotNumber: 1, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A008", fileNumber:"C006", sceneNumber: 30, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A008", fileNumber:"C007", sceneNumber: 30, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0704",rollNumber:"A008", fileNumber:"C008", sceneNumber: 30, shotNumber: 2, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.mls),
    ],
    "0705" :[
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A009", fileNumber:"C001", sceneNumber: 30, shotNumber: 2, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A009", fileNumber:"C002", sceneNumber: 30, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A009", fileNumber:"C003", sceneNumber: 30, shotNumber: 2, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A009", fileNumber:"C004", sceneNumber: 30, shotNumber: 2, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A009", fileNumber:"C005", sceneNumber: 30, shotNumber: 2, takeNumber: 5, result:.ok , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A009", fileNumber:"C006", sceneNumber: 30, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A009", fileNumber:"C007", sceneNumber: 30, shotNumber: 3, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C001", sceneNumber: 30, shotNumber: 3, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C002", sceneNumber: 30, shotNumber: 3, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C003", sceneNumber: 30, shotNumber: 3, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C004", sceneNumber: 30, shotNumber: 3, takeNumber: 6, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C005", sceneNumber: 30, shotNumber: 4, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C006", sceneNumber: 30, shotNumber: 4, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C007", sceneNumber: 30, shotNumber: 4, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C008", sceneNumber: 30, shotNumber: 4, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C009", sceneNumber: 30, shotNumber: 4, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C010", sceneNumber: 30, shotNumber: 4, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C011", sceneNumber: 30, shotNumber: 4, takeNumber: 7, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0705",rollNumber:"A010", fileNumber:"C012", sceneNumber: 30, shotNumber: 5, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.xls),
    ],
    "0706" :[
        ContinuitySheetRecording(createdDate:"0706",rollNumber:"A011", fileNumber:"C001", sceneNumber: 30, shotNumber: 5, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0706",rollNumber:"A012", fileNumber:"C001", sceneNumber: 30, shotNumber: 5, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0706",rollNumber:"A012", fileNumber:"C002", sceneNumber: 30, shotNumber: 5, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0706",rollNumber:"A012", fileNumber:"C003", sceneNumber: 30, shotNumber: 5, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0706",rollNumber:"A012", fileNumber:"C004", sceneNumber: 30, shotNumber: 5, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0706",rollNumber:"A012", fileNumber:"C005", sceneNumber: 30, shotNumber: 5, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0706",rollNumber:"A012", fileNumber:"C006", sceneNumber: 30, shotNumber: 5, takeNumber: 8, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0706",rollNumber:"A012", fileNumber:"C007", sceneNumber: 30, shotNumber: 5, takeNumber: 9, result:.ng , synopsis:" " , shotSize:.ms),
    ],
    "0707" :[
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C001", sceneNumber: 32, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C002", sceneNumber: 32, shotNumber: 1, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C003", sceneNumber: 32, shotNumber: 2, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C004", sceneNumber: 32, shotNumber: 2, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C005", sceneNumber: 32, shotNumber: 2, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C006", sceneNumber: 32, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C007", sceneNumber: 32, shotNumber: 3, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C008", sceneNumber: 32, shotNumber: 3, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C009", sceneNumber: 32, shotNumber: 3, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C010", sceneNumber: 32, shotNumber: 4, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C011", sceneNumber: 32, shotNumber: 4, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C012", sceneNumber: 32, shotNumber: 4, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C013", sceneNumber: 34, shotNumber: 1, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C014", sceneNumber: 34, shotNumber: 1, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C015", sceneNumber: 34, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A013", fileNumber:"C016", sceneNumber: 34, shotNumber: 1, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C001", sceneNumber: 34, shotNumber: 1, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C002", sceneNumber: 34, shotNumber: 2, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C003", sceneNumber: 34, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C004", sceneNumber: 34, shotNumber: 2, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C005", sceneNumber: 34, shotNumber: 2, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C006", sceneNumber: 34, shotNumber: 2, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C007", sceneNumber: 34, shotNumber: 2, takeNumber: 6, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C008", sceneNumber: 34, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C009", sceneNumber: 34, shotNumber: 3, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C010", sceneNumber: 34, shotNumber: 3, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C011", sceneNumber: 34, shotNumber: 3, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0707",rollNumber:"A014", fileNumber:"C012", sceneNumber: 34, shotNumber: 3, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.mcu),
    ],
    "0708" :[
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A015", fileNumber:"C001", sceneNumber: 35, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A015", fileNumber:"C002", sceneNumber: 35, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A015", fileNumber:"C003", sceneNumber: 35, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A015", fileNumber:"C004", sceneNumber: 35, shotNumber: 1, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A015", fileNumber:"C005", sceneNumber: 35, shotNumber: 1, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A015", fileNumber:"C006", sceneNumber: 35, shotNumber: 1, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A015", fileNumber:"C007", sceneNumber: 35, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A015", fileNumber:"C008", sceneNumber: 35, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A015", fileNumber:"C009", sceneNumber: 35, shotNumber: 2, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A015", fileNumber:"C010", sceneNumber: 35, shotNumber: 2, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A015", fileNumber:"C011", sceneNumber: 35, shotNumber: 2, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C001", sceneNumber: 35, shotNumber: 2, takeNumber: 6, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C002", sceneNumber: 35, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C003", sceneNumber: 35, shotNumber: 3, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C004", sceneNumber: 35, shotNumber: 3, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C005", sceneNumber: 35, shotNumber: 3, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C006", sceneNumber: 35, shotNumber: 3, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C007", sceneNumber: 35, shotNumber: 3, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C008", sceneNumber: 35, shotNumber: 3, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C009", sceneNumber: 35, shotNumber: 4, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C010", sceneNumber: 35, shotNumber: 4, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C011", sceneNumber: 35, shotNumber: 4, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C012", sceneNumber: 35, shotNumber: 4, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0708",rollNumber:"A016", fileNumber:"C013", sceneNumber: 35, shotNumber: 4, takeNumber: 5, result:.ok , synopsis:" " , shotSize:.ms),
    ],
    "0709" :[
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C001", sceneNumber: 36, shotNumber: 1, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C002", sceneNumber: 36, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C003", sceneNumber: 36, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C004", sceneNumber: 36, shotNumber: 1, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C005", sceneNumber: 36, shotNumber: 2, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C006", sceneNumber: 36, shotNumber: 2, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C007", sceneNumber: 36, shotNumber: 2, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C008", sceneNumber: 36, shotNumber: 2, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C009", sceneNumber: 36, shotNumber: 3, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C010", sceneNumber: 36, shotNumber: 3, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C011", sceneNumber: 36, shotNumber: 3, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C012", sceneNumber: 36, shotNumber: 3, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C013", sceneNumber: 36, shotNumber: 4, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C014", sceneNumber: 36, shotNumber: 4, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C015", sceneNumber: 36, shotNumber: 4, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C016", sceneNumber: 36, shotNumber: 4, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C017", sceneNumber: 36, shotNumber: 4, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C018", sceneNumber: 36, shotNumber: 5, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A017", fileNumber:"C019", sceneNumber: 36, shotNumber: 5, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C001", sceneNumber: 36, shotNumber: 5, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C002", sceneNumber: 37, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C003", sceneNumber: 37, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C004", sceneNumber: 37, shotNumber: 1, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C005", sceneNumber: 37, shotNumber: 1, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C006", sceneNumber: 37, shotNumber: 1, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C007", sceneNumber: 37, shotNumber: 1, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C008", sceneNumber: 37, shotNumber: 1, takeNumber: 7, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C009", sceneNumber: 37, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C010", sceneNumber: 37, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C011", sceneNumber: 37, shotNumber: 2, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C012", sceneNumber: 37, shotNumber: 2, takeNumber: 4, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C013", sceneNumber: 37, shotNumber: 2, takeNumber: 5, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C014", sceneNumber: 37, shotNumber: 2, takeNumber: 6, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C015", sceneNumber: 37, shotNumber: 2, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C016", sceneNumber: 37, shotNumber: 3, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C017", sceneNumber: 37, shotNumber: 3, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0709",rollNumber:"A018", fileNumber:"C018", sceneNumber: 37, shotNumber: 3, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ls),
    ],
    "0710" :[
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A019", fileNumber:"C001", sceneNumber: 30, shotNumber: 6, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A019", fileNumber:"C002", sceneNumber: 30, shotNumber: 6, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A019", fileNumber:"C003", sceneNumber: 30, shotNumber: 6, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A019", fileNumber:"C004", sceneNumber: 30, shotNumber: 6, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A019", fileNumber:"C005", sceneNumber: 30, shotNumber: 6, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A019", fileNumber:"C006", sceneNumber: 30, shotNumber: 6, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A019", fileNumber:"C007", sceneNumber: 30, shotNumber: 6, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A019", fileNumber:"C008", sceneNumber: 30, shotNumber: 6, takeNumber: 8, result:.ok , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A019", fileNumber:"C009", sceneNumber: 30, shotNumber: 6, takeNumber: 9, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A019", fileNumber:"C010", sceneNumber: 30, shotNumber: 7, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A019", fileNumber:"C011", sceneNumber: 30, shotNumber: 7, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A020", fileNumber:"C001", sceneNumber: 30, shotNumber: 7, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A020", fileNumber:"C002", sceneNumber: 30, shotNumber: 7, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0710",rollNumber:"A020", fileNumber:"C003", sceneNumber: 30, shotNumber: 7, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.xls),
    ],
    "0711" :[
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C001", sceneNumber: 38, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C002", sceneNumber: 38, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C003", sceneNumber: 38, shotNumber: 1, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C004", sceneNumber: 38, shotNumber: 1, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C005", sceneNumber: 38, shotNumber: 1, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C006", sceneNumber: 38, shotNumber: 1, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C007", sceneNumber: 38, shotNumber: 1, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C008", sceneNumber: 38, shotNumber: 1, takeNumber: 8, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C009", sceneNumber: 38, shotNumber: 2, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C010", sceneNumber: 38, shotNumber: 2, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C011", sceneNumber: 38, shotNumber: 2, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C012", sceneNumber: 38, shotNumber: 2, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C013", sceneNumber: 38, shotNumber: 2, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C014", sceneNumber: 38, shotNumber: 2, takeNumber: 6, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C015", sceneNumber: 38, shotNumber: 3, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C016", sceneNumber: 38, shotNumber: 3, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A021", fileNumber:"C017", sceneNumber: 38, shotNumber: 3, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C001", sceneNumber: 38, shotNumber: 3, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C002", sceneNumber: 38, shotNumber: 3, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C003", sceneNumber: 38, shotNumber: 3, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C004", sceneNumber: 38, shotNumber: 3, takeNumber: 7, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C005", sceneNumber: 38, shotNumber: 3, takeNumber: 8, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C006", sceneNumber: 38, shotNumber: 3, takeNumber: 9, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C007", sceneNumber: 38, shotNumber: 3, takeNumber: 10, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C008", sceneNumber: 38, shotNumber: 4, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C009", sceneNumber: 39, shotNumber: 1, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C010", sceneNumber: 39, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C011", sceneNumber: 39, shotNumber: 1, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C012", sceneNumber: 39, shotNumber: 1, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C013", sceneNumber: 39, shotNumber: 1, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C014", sceneNumber: 39, shotNumber: 1, takeNumber: 6, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C015", sceneNumber: 39, shotNumber: 1, takeNumber: 7, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C016", sceneNumber: 39, shotNumber: 1, takeNumber: 8, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0711",rollNumber:"A022", fileNumber:"C017", sceneNumber: 39, shotNumber: 1, takeNumber: 9, result:.ok , synopsis:" " , shotSize:.cu),
    ],
    "0712" :[
        ContinuitySheetRecording(createdDate:"0712",rollNumber:"A023", fileNumber:"C001", sceneNumber: 46, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0712",rollNumber:"A024", fileNumber:"C001", sceneNumber: 46, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0712",rollNumber:"A024", fileNumber:"C002", sceneNumber: 46, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0712",rollNumber:"A024", fileNumber:"C003", sceneNumber: 46, shotNumber: 2, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0712",rollNumber:"A024", fileNumber:"C004", sceneNumber: 46, shotNumber: 2, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0712",rollNumber:"A024", fileNumber:"C005", sceneNumber: 46, shotNumber: 2, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0712",rollNumber:"A024", fileNumber:"C006", sceneNumber: 46, shotNumber: 2, takeNumber: 4, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0712",rollNumber:"A024", fileNumber:"C007", sceneNumber: 46, shotNumber: 2, takeNumber: 5, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0712",rollNumber:"A024", fileNumber:"C008", sceneNumber: 46, shotNumber: 2, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.xls),
    ],
    "0713" :[
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C001", sceneNumber: 46, shotNumber: 3, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C002", sceneNumber: 46, shotNumber: 3, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C003", sceneNumber: 46, shotNumber: 4, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C004", sceneNumber: 48, shotNumber: 1, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C005", sceneNumber: 48, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C006", sceneNumber: 48, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C007", sceneNumber: 48, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C008", sceneNumber: 48, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C009", sceneNumber: 48, shotNumber: 2, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C010", sceneNumber: 48, shotNumber: 3, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C011", sceneNumber: 48, shotNumber: 3, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C012", sceneNumber: 48, shotNumber: 3, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C013", sceneNumber: 48, shotNumber: 3, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C014", sceneNumber: 48, shotNumber: 3, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C015", sceneNumber: 48, shotNumber: 3, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A025", fileNumber:"C016", sceneNumber: 48, shotNumber: 4, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A026", fileNumber:"C001", sceneNumber: 48, shotNumber: 4, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A026", fileNumber:"C002", sceneNumber: 48, shotNumber: 4, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A026", fileNumber:"C003", sceneNumber: 48, shotNumber: 4, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A026", fileNumber:"C004", sceneNumber: 48, shotNumber: 5, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A026", fileNumber:"C005", sceneNumber: 48, shotNumber: 5, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A026", fileNumber:"C006", sceneNumber: 48, shotNumber: 5, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A026", fileNumber:"C007", sceneNumber: 48, shotNumber: 5, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0713",rollNumber:"A026", fileNumber:"C008", sceneNumber: 48, shotNumber: 6, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.mcu),
    ],
    "0714" :[
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A027", fileNumber:"C001", sceneNumber: 6, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A027", fileNumber:"C002", sceneNumber: 6, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A027", fileNumber:"C003", sceneNumber: 6, shotNumber: 1, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A027", fileNumber:"C004", sceneNumber: 6, shotNumber: 1, takeNumber: 4, result:.kp , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A028", fileNumber:"C001", sceneNumber: 6, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A028", fileNumber:"C002", sceneNumber: 6, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A028", fileNumber:"C003", sceneNumber: 6, shotNumber: 2, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A028", fileNumber:"C004", sceneNumber: 6, shotNumber: 2, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A028", fileNumber:"C005", sceneNumber: 6, shotNumber: 2, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A028", fileNumber:"C006", sceneNumber: 6, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A028", fileNumber:"C007", sceneNumber: 6, shotNumber: 3, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A028", fileNumber:"C008", sceneNumber: 6, shotNumber: 3, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0714",rollNumber:"A028", fileNumber:"C009", sceneNumber: 6, shotNumber: 3, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.mls),
    ],
    "0715" :[
        ContinuitySheetRecording(createdDate:"0715",rollNumber:"A029", fileNumber:"C001", sceneNumber: 9, shotNumber: 1, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0715",rollNumber:"A029", fileNumber:"C002", sceneNumber: 9, shotNumber: 1, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0715",rollNumber:"A029", fileNumber:"C003", sceneNumber: 9, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0715",rollNumber:"A029", fileNumber:"C004", sceneNumber: 9, shotNumber: 1, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0715",rollNumber:"A029", fileNumber:"C005", sceneNumber: 9, shotNumber: 1, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0715",rollNumber:"A029", fileNumber:"C006", sceneNumber: 9, shotNumber: 1, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0715",rollNumber:"A029", fileNumber:"C007", sceneNumber: 9, shotNumber: 1, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0715",rollNumber:"A030", fileNumber:"C001", sceneNumber: 9, shotNumber: 1, takeNumber: 8, result:.ng , synopsis:" " , shotSize:.xls),
    ],
    "0716" :[
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A031", fileNumber:"C001", sceneNumber: 18, shotNumber: 1, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A031", fileNumber:"C002", sceneNumber: 18, shotNumber: 1, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A031", fileNumber:"C003", sceneNumber: 18, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A031", fileNumber:"C004", sceneNumber: 18, shotNumber: 1, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A031", fileNumber:"C005", sceneNumber: 18, shotNumber: 1, takeNumber: 5, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A031", fileNumber:"C006", sceneNumber: 18, shotNumber: 1, takeNumber: 6, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C001", sceneNumber: 18, shotNumber: 1, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C002", sceneNumber: 18, shotNumber: 1, takeNumber: 8, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C003", sceneNumber: 18, shotNumber: 1, takeNumber: 9, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C004", sceneNumber: 18, shotNumber: 1, takeNumber: 10, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C005", sceneNumber: 18, shotNumber: 1, takeNumber: 11, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C006", sceneNumber: 18, shotNumber: 2, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C007", sceneNumber: 18, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C008", sceneNumber: 18, shotNumber: 2, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C009", sceneNumber: 19, shotNumber: 1, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C010", sceneNumber: 19, shotNumber: 1, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C011", sceneNumber: 19, shotNumber: 1, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C012", sceneNumber: 19, shotNumber: 1, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C013", sceneNumber: 19, shotNumber: 2, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C014", sceneNumber: 19, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C015", sceneNumber: 19, shotNumber: 2, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0716",rollNumber:"A032", fileNumber:"C016", sceneNumber: 19, shotNumber: 2, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.mls),
    ],
    "0717" :[
        ContinuitySheetRecording(createdDate:"0717",rollNumber:"A033", fileNumber:"C001", sceneNumber: 19, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0717",rollNumber:"A033", fileNumber:"C002", sceneNumber: 19, shotNumber: 3, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0717",rollNumber:"A033", fileNumber:"C003", sceneNumber: 19, shotNumber: 3, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0717",rollNumber:"A034", fileNumber:"C001", sceneNumber: 19, shotNumber: 3, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0717",rollNumber:"A034", fileNumber:"C002", sceneNumber: 19, shotNumber: 3, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0717",rollNumber:"A034", fileNumber:"C003", sceneNumber: 19, shotNumber: 4, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0717",rollNumber:"A034", fileNumber:"C004", sceneNumber: 19, shotNumber: 4, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0717",rollNumber:"A034", fileNumber:"C005", sceneNumber: 19, shotNumber: 4, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ls),
    ],
    "0718" :[
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A035", fileNumber:"C001", sceneNumber: 19, shotNumber: 4, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A035", fileNumber:"C002", sceneNumber: 19, shotNumber: 4, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A035", fileNumber:"C003", sceneNumber: 19, shotNumber: 5, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A035", fileNumber:"C004", sceneNumber: 19, shotNumber: 6, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A035", fileNumber:"C005", sceneNumber: 23, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A035", fileNumber:"C006", sceneNumber: 23, shotNumber: 1, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A035", fileNumber:"C007", sceneNumber: 23, shotNumber: 1, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A035", fileNumber:"C008", sceneNumber: 23, shotNumber: 1, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C001", sceneNumber: 23, shotNumber: 1, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C002", sceneNumber: 23, shotNumber: 2, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C003", sceneNumber: 23, shotNumber: 2, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C004", sceneNumber: 23, shotNumber: 2, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C005", sceneNumber: 23, shotNumber: 2, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C006", sceneNumber: 23, shotNumber: 2, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C007", sceneNumber: 23, shotNumber: 2, takeNumber: 6, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C008", sceneNumber: 23, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C009", sceneNumber: 23, shotNumber: 3, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C010", sceneNumber: 23, shotNumber: 3, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C011", sceneNumber: 23, shotNumber: 3, takeNumber: 4, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C012", sceneNumber: 23, shotNumber: 3, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C013", sceneNumber: 23, shotNumber: 3, takeNumber: 6, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C014", sceneNumber: 23, shotNumber: 3, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C015", sceneNumber: 23, shotNumber: 3, takeNumber: 8, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C016", sceneNumber: 24, shotNumber: 1, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C017", sceneNumber: 24, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0718",rollNumber:"A036", fileNumber:"C018", sceneNumber: 24, shotNumber: 1, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.ls),
    ],
    "0719" :[
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A037", fileNumber:"C001", sceneNumber: 24, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A037", fileNumber:"C002", sceneNumber: 24, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A037", fileNumber:"C003", sceneNumber: 24, shotNumber: 2, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A037", fileNumber:"C004", sceneNumber: 24, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A037", fileNumber:"C005", sceneNumber: 24, shotNumber: 3, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A037", fileNumber:"C006", sceneNumber: 24, shotNumber: 3, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A037", fileNumber:"C007", sceneNumber: 24, shotNumber: 3, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A037", fileNumber:"C008", sceneNumber: 24, shotNumber: 3, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C001", sceneNumber: 24, shotNumber: 4, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C002", sceneNumber: 24, shotNumber: 4, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C003", sceneNumber: 24, shotNumber: 4, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C004", sceneNumber: 24, shotNumber: 4, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C005", sceneNumber: 24, shotNumber: 5, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C006", sceneNumber: 24, shotNumber: 5, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C007", sceneNumber: 24, shotNumber: 5, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C008", sceneNumber: 24, shotNumber: 5, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C009", sceneNumber: 24, shotNumber: 5, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C010", sceneNumber: 24, shotNumber: 5, takeNumber: 6, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C011", sceneNumber: 24, shotNumber: 5, takeNumber: 7, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C012", sceneNumber: 24, shotNumber: 6, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C013", sceneNumber: 24, shotNumber: 6, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C014", sceneNumber: 24, shotNumber: 6, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C015", sceneNumber: 24, shotNumber: 6, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0719",rollNumber:"A038", fileNumber:"C016", sceneNumber: 24, shotNumber: 6, takeNumber: 5, result:.ok , synopsis:" " , shotSize:.bcu),
    ],
    "0720" :[
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A039", fileNumber:"C001", sceneNumber: 25, shotNumber: 4, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A039", fileNumber:"C002", sceneNumber: 25, shotNumber: 4, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A039", fileNumber:"C003", sceneNumber: 25, shotNumber: 4, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A039", fileNumber:"C004", sceneNumber: 25, shotNumber: 4, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A039", fileNumber:"C005", sceneNumber: 25, shotNumber: 5, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A039", fileNumber:"C006", sceneNumber: 25, shotNumber: 5, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A039", fileNumber:"C007", sceneNumber: 25, shotNumber: 5, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A039", fileNumber:"C008", sceneNumber: 25, shotNumber: 5, takeNumber: 4, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A040", fileNumber:"C001", sceneNumber: 25, shotNumber: 5, takeNumber: 5, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A040", fileNumber:"C002", sceneNumber: 25, shotNumber: 5, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A040", fileNumber:"C003", sceneNumber: 25, shotNumber: 5, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A040", fileNumber:"C004", sceneNumber: 25, shotNumber: 5, takeNumber: 8, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A040", fileNumber:"C005", sceneNumber: 25, shotNumber: 6, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A040", fileNumber:"C006", sceneNumber: 25, shotNumber: 6, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A040", fileNumber:"C007", sceneNumber: 25, shotNumber: 6, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A040", fileNumber:"C008", sceneNumber: 25, shotNumber: 6, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A040", fileNumber:"C009", sceneNumber: 25, shotNumber: 6, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A040", fileNumber:"C010", sceneNumber: 26, shotNumber: 1, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0720",rollNumber:"A040", fileNumber:"C011", sceneNumber: 26, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.xls),
    ],
    "0721" :[
        ContinuitySheetRecording(createdDate:"0721",rollNumber:"A042", fileNumber:"C001", sceneNumber: 26, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0721",rollNumber:"A042", fileNumber:"C002", sceneNumber: 26, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0721",rollNumber:"A042", fileNumber:"C003", sceneNumber: 26, shotNumber: 2, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.ls),
    ],
    "0722" :[
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A043", fileNumber:"C001", sceneNumber: 26, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A043", fileNumber:"C002", sceneNumber: 26, shotNumber: 3, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A043", fileNumber:"C003", sceneNumber: 26, shotNumber: 3, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C001", sceneNumber: 26, shotNumber: 3, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C002", sceneNumber: 26, shotNumber: 3, takeNumber: 5, result:.ok , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C003", sceneNumber: 26, shotNumber: 4, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C004", sceneNumber: 26, shotNumber: 4, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C005", sceneNumber: 26, shotNumber: 4, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C006", sceneNumber: 26, shotNumber: 4, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C007", sceneNumber: 26, shotNumber: 4, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C008", sceneNumber: 26, shotNumber: 4, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C009", sceneNumber: 26, shotNumber: 5, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C010", sceneNumber: 26, shotNumber: 5, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C011", sceneNumber: 26, shotNumber: 5, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0722",rollNumber:"A044", fileNumber:"C012", sceneNumber: 26, shotNumber: 5, takeNumber: 4, result:.kp , synopsis:" " , shotSize:.mls),
    ],
    "0723" :[
        ContinuitySheetRecording(createdDate:"0723",rollNumber:"A045", fileNumber:"C001", sceneNumber: 27, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0723",rollNumber:"A045", fileNumber:"C002", sceneNumber: 27, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0723",rollNumber:"A046", fileNumber:"C001", sceneNumber: 27, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0723",rollNumber:"A046", fileNumber:"C002", sceneNumber: 27, shotNumber: 1, takeNumber: 4, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0723",rollNumber:"A046", fileNumber:"C003", sceneNumber: 27, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0723",rollNumber:"A046", fileNumber:"C004", sceneNumber: 27, shotNumber: 2, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0723",rollNumber:"A046", fileNumber:"C005", sceneNumber: 27, shotNumber: 2, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.ls),
    ],
    "0724" :[
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A047", fileNumber:"C001", sceneNumber: 28, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A047", fileNumber:"C002", sceneNumber: 28, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A047", fileNumber:"C003", sceneNumber: 28, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A047", fileNumber:"C004", sceneNumber: 28, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A047", fileNumber:"C005", sceneNumber: 28, shotNumber: 2, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A047", fileNumber:"C006", sceneNumber: 28, shotNumber: 2, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A047", fileNumber:"C007", sceneNumber: 28, shotNumber: 2, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A047", fileNumber:"C008", sceneNumber: 28, shotNumber: 2, takeNumber: 6, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A047", fileNumber:"C009", sceneNumber: 28, shotNumber: 2, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A048", fileNumber:"C001", sceneNumber: 28, shotNumber: 2, takeNumber: 8, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A048", fileNumber:"C002", sceneNumber: 28, shotNumber: 2, takeNumber: 9, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A048", fileNumber:"C003", sceneNumber: 28, shotNumber: 2, takeNumber: 10, result:.ok , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A048", fileNumber:"C004", sceneNumber: 28, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A048", fileNumber:"C005", sceneNumber: 28, shotNumber: 3, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0724",rollNumber:"A048", fileNumber:"C006", sceneNumber: 28, shotNumber: 3, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.ms),
    ],
    "0725" :[
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C001", sceneNumber: 2, shotNumber: 1, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C002", sceneNumber: 2, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C003", sceneNumber: 2, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C004", sceneNumber: 2, shotNumber: 1, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C005", sceneNumber: 2, shotNumber: 1, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C006", sceneNumber: 2, shotNumber: 1, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C007", sceneNumber: 2, shotNumber: 1, takeNumber: 7, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C008", sceneNumber: 2, shotNumber: 1, takeNumber: 8, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C009", sceneNumber: 2, shotNumber: 2, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C010", sceneNumber: 2, shotNumber: 2, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C011", sceneNumber: 1, shotNumber: 1, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C012", sceneNumber: 1, shotNumber: 1, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C013", sceneNumber: 1, shotNumber: 1, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C014", sceneNumber: 1, shotNumber: 1, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C015", sceneNumber: 1, shotNumber: 1, takeNumber: 5, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0725",rollNumber:"A050", fileNumber:"C016", sceneNumber: 1, shotNumber: 1, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.bcu),
    ],
    "0726" :[
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A051", fileNumber:"C001", sceneNumber: 3, shotNumber: 1, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A051", fileNumber:"C002", sceneNumber: 3, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A051", fileNumber:"C003", sceneNumber: 3, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C001", sceneNumber: 3, shotNumber: 1, takeNumber: 4, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C002", sceneNumber: 3, shotNumber: 1, takeNumber: 5, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C003", sceneNumber: 3, shotNumber: 1, takeNumber: 6, result:.ok , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C004", sceneNumber: 3, shotNumber: 1, takeNumber: 7, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C005", sceneNumber: 4, shotNumber: 1, takeNumber: 8, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C006", sceneNumber: 4, shotNumber: 1, takeNumber: 9, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C007", sceneNumber: 4, shotNumber: 2, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C008", sceneNumber: 4, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C009", sceneNumber: 4, shotNumber: 2, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C010", sceneNumber: 4, shotNumber: 2, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C011", sceneNumber: 4, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C012", sceneNumber: 4, shotNumber: 3, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C013", sceneNumber: 4, shotNumber: 3, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C014", sceneNumber: 4, shotNumber: 3, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0726",rollNumber:"A052", fileNumber:"C015", sceneNumber: 4, shotNumber: 4, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.vls),
    ],
    "0727" :[
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A053", fileNumber:"C001", sceneNumber: 4, shotNumber: 4, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A053", fileNumber:"C002", sceneNumber: 4, shotNumber: 4, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A053", fileNumber:"C003", sceneNumber: 4, shotNumber: 5, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A053", fileNumber:"C004", sceneNumber: 4, shotNumber: 5, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A053", fileNumber:"C005", sceneNumber: 4, shotNumber: 5, takeNumber: 3, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C001", sceneNumber: 4, shotNumber: 5, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C002", sceneNumber: 4, shotNumber: 6, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C003", sceneNumber: 4, shotNumber: 6, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C004", sceneNumber: 4, shotNumber: 6, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C005", sceneNumber: 4, shotNumber: 6, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C006", sceneNumber: 4, shotNumber: 6, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C007", sceneNumber: 4, shotNumber: 7, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C008", sceneNumber: 4, shotNumber: 7, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C009", sceneNumber: 4, shotNumber: 7, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C010", sceneNumber: 10, shotNumber: 1, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C011", sceneNumber: 10, shotNumber: 1, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C012", sceneNumber: 10, shotNumber: 1, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C013", sceneNumber: 10, shotNumber: 1, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0727",rollNumber:"A054", fileNumber:"C014", sceneNumber: 10, shotNumber: 1, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.mls),
    ],
    "0728" :[
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C001", sceneNumber: 10, shotNumber: 2, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C002", sceneNumber: 10, shotNumber: 2, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C003", sceneNumber: 10, shotNumber: 2, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C004", sceneNumber: 10, shotNumber: 2, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C005", sceneNumber: 10, shotNumber: 3, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C006", sceneNumber: 10, shotNumber: 3, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C007", sceneNumber: 10, shotNumber: 3, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C008", sceneNumber: 10, shotNumber: 3, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C009", sceneNumber: 10, shotNumber: 3, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C010", sceneNumber: 10, shotNumber: 3, takeNumber: 6, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C011", sceneNumber: 10, shotNumber: 4, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C012", sceneNumber: 10, shotNumber: 4, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A055", fileNumber:"C013", sceneNumber: 10, shotNumber: 4, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0728",rollNumber:"A056", fileNumber:"C001", sceneNumber: 10, shotNumber: 4, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.mls),
    ],
    "0729" :[
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C001", sceneNumber: 19, shotNumber: 7, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C002", sceneNumber: 19, shotNumber: 7, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C003", sceneNumber: 19, shotNumber: 7, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C004", sceneNumber: 19, shotNumber: 7, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C005", sceneNumber: 19, shotNumber: 7, takeNumber: 5, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C006", sceneNumber: 19, shotNumber: 7, takeNumber: 6, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C007", sceneNumber: 19, shotNumber: 8, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C008", sceneNumber: 19, shotNumber: 8, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C009", sceneNumber: 19, shotNumber: 8, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C010", sceneNumber: 19, shotNumber: 8, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C011", sceneNumber: 19, shotNumber: 9, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C012", sceneNumber: 19, shotNumber: 9, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C013", sceneNumber: 19, shotNumber: 9, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C014", sceneNumber: 19, shotNumber: 9, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A057", fileNumber:"C015", sceneNumber: 19, shotNumber: 10, takeNumber:1 , result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C001", sceneNumber: 45, shotNumber: 1, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C002", sceneNumber: 45, shotNumber: 1, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C003", sceneNumber: 45, shotNumber: 1, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C004", sceneNumber: 45, shotNumber: 1, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C005", sceneNumber: 45, shotNumber: 2, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C006", sceneNumber: 45, shotNumber: 2, takeNumber: 2, result:.kp , synopsis:" " , shotSize:.mls),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C007", sceneNumber: 45, shotNumber: 2, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C008", sceneNumber: 45, shotNumber: 2, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C009", sceneNumber: 45, shotNumber: 2, takeNumber: 5, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C010", sceneNumber: 45, shotNumber: 3, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C011", sceneNumber: 45, shotNumber: 3, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C012", sceneNumber: 45, shotNumber: 3, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.cu),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C013", sceneNumber: 45, shotNumber: 3, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0729",rollNumber:"A058", fileNumber:"C014", sceneNumber: 45, shotNumber: 3, takeNumber: 5, result:.ok , synopsis:" " , shotSize:.xls),
    ],
    "0730" :[
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A059", fileNumber:"C001", sceneNumber: 45, shotNumber: 4, takeNumber: 1, result:.ok , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A059", fileNumber:"C002", sceneNumber: 45, shotNumber: 4, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A059", fileNumber:"C003", sceneNumber: 45, shotNumber: 4, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A059", fileNumber:"C004", sceneNumber: 45, shotNumber: 5, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.ms),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A060", fileNumber:"C001", sceneNumber: 45, shotNumber: 5, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A060", fileNumber:"C002", sceneNumber: 45, shotNumber: 5, takeNumber: 3, result:.ok , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A060", fileNumber:"C003", sceneNumber: 45, shotNumber: 5, takeNumber: 4, result:.ok , synopsis:" " , shotSize:.mcu),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A060", fileNumber:"C004", sceneNumber: 45, shotNumber: 6, takeNumber: 1, result:.kp , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A060", fileNumber:"C005", sceneNumber: 45, shotNumber: 7, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A060", fileNumber:"C006", sceneNumber: 45, shotNumber: 7, takeNumber: 2, result:.ng , synopsis:" " , shotSize:.vls),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A060", fileNumber:"C007", sceneNumber: 45, shotNumber: 7, takeNumber: 3, result:.ng , synopsis:" " , shotSize:.ls),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A060", fileNumber:"C008", sceneNumber: 45, shotNumber: 7, takeNumber: 4, result:.ng , synopsis:" " , shotSize:.bcu),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A060", fileNumber:"C009", sceneNumber: 45, shotNumber: 8, takeNumber: 1, result:.ng , synopsis:" " , shotSize:.xls),
        ContinuitySheetRecording(createdDate:"0730",rollNumber:"A060", fileNumber:"C010", sceneNumber: 45, shotNumber: 8, takeNumber: 2, result:.ok , synopsis:" " , shotSize:.ls),
    ]

]
